import { DirectoryTypes, FileTypes, IridiumItem } from "~/types/file";
import { User } from "~/types/global";

export const MOCK_USERS: User[] = [
  {
    did: "1",
    avatar: "https://placekitten.com/128/128",
    name: "joe",
    lastMessage:
      "hello00000000000000000000000000000000000000000000000000000000000000000000000000000000",
    lastMessageAt: Date.now(),
  },
  {
    did: "2",
    avatar: "https://placekitten.com/128/128",
    name: "nate",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "3",
    avatar: "https://placekitten.com/128/128",
    name: "j bone",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "4",
    avatar: "https://placekitten.com/128/128",
    name: "dongle",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "5",
    avatar: "https://placekitten.com/128/128",
    name: "dingle",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "6",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "7",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "8",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "9",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "10",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "11",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "12",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "13",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
  {
    did: "14",
    avatar: "https://placekitten.com/128/128",
    name: "super long name test blahskdhajshdjh",
    lastMessage: "hello",
    lastMessageAt: Date.now(),
  },
];

export const MOCK_ITEMS: IridiumItem[] = [
  {
    id: "2",
    name: "empty folder",
    liked: true,
    shared: false,
    modifiedAt: 23764278934,
    size: 0,
    parentId: "",
    type: DirectoryTypes.DEFAULT,
    children: [],
  },
  {
    id: "3",
    name: "folder with children",
    liked: false,
    shared: false,
    modifiedAt: 23764278934,
    size: 0,
    parentId: "",
    type: DirectoryTypes.DEFAULT,
    children: [
      {
        id: "1",
        name: "test.png",
        liked: true,
        shared: false,
        modifiedAt: 23764278934,
        size: 200,
        parentId: "5",
        type: FileTypes.PNG,
        thumbnail: "",
        extension: ".png",
        nsfw: false,
      },
      {
        id: "4",
        name: "2nd level child with children",
        liked: true,
        shared: false,
        modifiedAt: 23764278934,
        size: 0,
        parentId: "3",
        type: DirectoryTypes.DEFAULT,
        children: [
          {
            id: "6",
            name: "incredibly long folder name slkdjflksjdkl;fjsl;djfklsjldfjslk;dfjsldkfjlsdjfweoifpwjefodfjsldkfjlsdjfweoifpwjefodfjsldkfjlsdjfweoifpwjefodfjsldkfjlsdjfweoifpwjefo",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "4",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
        ],
      },
      {
        id: "5",
        name: "trigger overflow",
        liked: true,
        shared: false,
        modifiedAt: 23764278934,
        size: 0,
        parentId: "3",
        type: DirectoryTypes.DEFAULT,
        children: [
          {
            id: "8",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "9",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "10",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "11",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "12",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "13",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "14",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "15",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "16",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "17",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "18",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "19",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "20",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "21",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "22",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "23",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "24",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "25",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "26",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "27",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "28",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
          {
            id: "29",
            name: "trigger overflow",
            liked: true,
            shared: false,
            modifiedAt: 23764278934,
            size: 0,
            parentId: "5",
            type: DirectoryTypes.DEFAULT,
            children: [],
          },
        ],
      },
    ],
  },
];
